"""splent_feature_auth

Revision ID: a1fb31611281
Revises: 990210b54b52
Create Date: 2026-03-21 18:47:37.255641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fb31611281'
down_revision = '990210b54b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
