"""splent_feature_auth

Revision ID: fd0b989746d8
Revises: 5ad9fd0688b1
Create Date: 2026-03-21 23:53:13.114307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0b989746d8'
down_revision = '5ad9fd0688b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
